import type { Metadata } from 'next';
import { Tac_One, JetBrains_Mono } from 'next/font/google';
import StyledComponentsRegistry from '@/lib/registry';
import { ThemeProviderWrapper } from '@/providers/ThemeProvider';
import HeaderController from '@/components/Headers/HeaderController';

const jetBrains = JetBrains_Mono({
  variable: '--font-text',
  subsets: ['latin'],
  style: ['italic', 'normal'],
  weight: ['100', '200', '300', '600', '800'],
});

const tacOne = Tac_One({
  variable: '--font-title',
  subsets: ['latin'],
  style: 'normal',
  weight: '400',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${jetBrains.variable} ${tacOne.variable}`}>
        <StyledComponentsRegistry>
          <ThemeProviderWrapper>
            <HeaderController />
            {children}
          </ThemeProviderWrapper>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
